fixed Oh My ZSH installation

diff --git a/goAndo b/goAndo
--- a/goAndo
+++ b/goAndo
@@ -64,116 +64,116 @@ ask_for_sudo
 chapter 'Checking for SSH key…'
 ssh_key_setup
 
-###############################################################################
-# INSTALL: Dependencies
-###############################################################################
-chapter "Installing Dependencies…"
+# ###############################################################################
+# # INSTALL: Dependencies
+# ###############################################################################
+# chapter "Installing Dependencies…"
 
-# -----------------------------------------------------------------------------
-# XCode
-# -----------------------------------------------------------------------------
-if type xcode-select >&- && xpath=$( xcode-select --print-path ) &&
-	test -d "${xpath}" && test -x "${xpath}" ; then
-	print_success_muted "Xcode already installed. Skipping."
-else
-	step "Installing Xcode…"
-	xcode-select --install
-	print_success "Xcode installed!"
-fi
+# # -----------------------------------------------------------------------------
+# # XCode
+# # -----------------------------------------------------------------------------
+# if type xcode-select >&- && xpath=$( xcode-select --print-path ) &&
+# 	test -d "${xpath}" && test -x "${xpath}" ; then
+# 	print_success_muted "Xcode already installed. Skipping."
+# else
+# 	step "Installing Xcode…"
+# 	xcode-select --install
+# 	print_success "Xcode installed!"
+# fi
 
-if [ ! -d "$HOME/.bin/" ]; then
-	mkdir "$HOME/.bin"
-fi
+# if [ ! -d "$HOME/.bin/" ]; then
+# 	mkdir "$HOME/.bin"
+# fi
 
-# -----------------------------------------------------------------------------
-# Bash-it
-# -----------------------------------------------------------------------------
-if [ -d "$HOME/.bash_it" ]; then
-	print_success_muted "Bash-it already installed. Skipping."
-else
-	step "Installing Bash-it…"
-	git clone --depth=1 https://github.com/Bash-it/bash-it.git ~/.bash_it
-	~/.bash_it/install.sh --silent --no-modify-config
-	print_success "Bash-it installed!"
-fi
+# # -----------------------------------------------------------------------------
+# # Bash-it
+# # -----------------------------------------------------------------------------
+# if [ -d "$HOME/.bash_it" ]; then
+# 	print_success_muted "Bash-it already installed. Skipping."
+# else
+# 	step "Installing Bash-it…"
+# 	git clone --depth=1 https://github.com/Bash-it/bash-it.git ~/.bash_it
+# 	~/.bash_it/install.sh --silent --no-modify-config
+# 	print_success "Bash-it installed!"
+# fi
 
-# -----------------------------------------------------------------------------
-# NVM
-# -----------------------------------------------------------------------------
-if [ -x nvm ]; then
-	step "Installing NVM…"
-	curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
-	print_success "NVM installed!"
-	step "Installing latest Node…"
-	nvm install node
-	nvm use node
-	nvm run node --version
-	nodev=$(node -v)
-	print_success "Using Node $nodev!"
-else
-	print_success_muted "NVM/Node already installed. Skipping."
-fi
+# # -----------------------------------------------------------------------------
+# # NVM
+# # -----------------------------------------------------------------------------
+# if [ -x nvm ]; then
+# 	step "Installing NVM…"
+# 	curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
+# 	print_success "NVM installed!"
+# 	step "Installing latest Node…"
+# 	nvm install node
+# 	nvm use node
+# 	nvm run node --version
+# 	nodev=$(node -v)
+# 	print_success "Using Node $nodev!"
+# else
+# 	print_success_muted "NVM/Node already installed. Skipping."
+# fi
 
-# -----------------------------------------------------------------------------
-# Homebrew
-# -----------------------------------------------------------------------------
-if ! [ -x "$(command -v brew)" ]; then
-	step "Installing Homebrew…"
-	curl -fsS 'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby
-	export PATH="/usr/local/bin:$PATH"
-	print_success "Homebrew installed!"
-else
-	print_success_muted "Homebrew already installed. Skipping."
-fi
+# # -----------------------------------------------------------------------------
+# # Homebrew
+# # -----------------------------------------------------------------------------
+# if ! [ -x "$(command -v brew)" ]; then
+# 	step "Installing Homebrew…"
+# 	curl -fsS 'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby
+# 	export PATH="/usr/local/bin:$PATH"
+# 	print_success "Homebrew installed!"
+# else
+# 	print_success_muted "Homebrew already installed. Skipping."
+# fi
 
-if brew list | grep -Fq brew-cask; then
-	step "Uninstalling old Homebrew-Cask…"
-	brew uninstall --force brew-cask
-	print_success "Homebrew-Cask uninstalled!"
-fi
+# if brew list | grep -Fq brew-cask; then
+# 	step "Uninstalling old Homebrew-Cask…"
+# 	brew uninstall --force brew-cask
+# 	print_success "Homebrew-Cask uninstalled!"
+# fi
 
-###############################################################################
-# INSTALL: brews
-###############################################################################
-if [ -e $cwd/materials/brews ]; then
-	chapter "Installing Homebrew formulae…"
+# ###############################################################################
+# # INSTALL: brews
+# ###############################################################################
+# if [ -e $cwd/materials/brews ]; then
+# 	chapter "Installing Homebrew formulae…"
 
-	for brew in $(<$cwd/materials/brews); do
-		install_brews $brew
-	done
-fi
-
-
-###############################################################################
-# INSTALL: taps
-###############################################################################
-# if [ -e $cwd/materials/taps ]; then
-# 	chapter "Installing Homebrew taps…"
-
-# 	for brew in $(<$cwd/materials/taps); do
-# 		install_brew_taps $tap
+# 	for brew in $(<$cwd/materials/brews); do
+# 		install_brews $brew
 # 	done
 # fi
 
 
+# ###############################################################################
+# # INSTALL: taps
+# ###############################################################################
+# # if [ -e $cwd/materials/taps ]; then
+# # 	chapter "Installing Homebrew taps…"
+
+# # 	for brew in $(<$cwd/materials/taps); do
+# # 		install_brew_taps $tap
+# # 	done
+# # fi
 
 
-###############################################################################
-# UPDATE: Homebrew
-###############################################################################
-chapter "Updating Homebrew formulae…"
-brew update
 
-###############################################################################
-# INSTALL: casks
-###############################################################################
-if [ -e $cwd/materials/casks ]; then
-	chapter "Installing apps via Homebrew…"
 
-	for cask in $(<$cwd/materials/casks); do
-	    install_application_via_brew $cask
-	done
-fi
+# ###############################################################################
+# # UPDATE: Homebrew
+# ###############################################################################
+# chapter "Updating Homebrew formulae…"
+# brew update
+
+# ###############################################################################
+# # INSTALL: casks
+# ###############################################################################
+# if [ -e $cwd/materials/casks ]; then
+# 	chapter "Installing apps via Homebrew…"
+
+# 	for cask in $(<$cwd/materials/casks); do
+# 	    install_application_via_brew $cask
+# 	done
+# fi
 
 ###############################################################################
 # INSTALL: Mac App Store Apps
@@ -201,25 +201,43 @@ if [ -x mas ]; then
 
 fi
 
-###############################################################################
-# CLEAN: Homebrew files
-###############################################################################
-chapter "Cleaning up Homebrew files…"
-brew cleanup 2> /dev/null
+# ###############################################################################
+# # CLEAN: Homebrew files
+# ###############################################################################
+# chapter "Cleaning up Homebrew files…"
+# brew cleanup 2> /dev/null
+
+# ###############################################################################
+# # INSTALL: npm packages
+# ###############################################################################
+# if [ -e $cwd/materials/npm ]; then
+# 	chapter "Installing npm packages…"
+
+# 	for pkg in $(<$cwd/materials/npm); do
+# 		KEY="${pkg%%::*}"
+# 		VALUE="${pkg##*::}"
+# 		install_npm_packages $KEY $VALUE
+# 	done
+# fi
+
 
 ###############################################################################
-# INSTALL: npm packages
+# Install: Oh My ZSH
 ###############################################################################
-if [ -e $cwd/materials/npm ]; then
-	chapter "Installing npm packages…"
-
-	for pkg in $(<$cwd/materials/npm); do
-		KEY="${pkg%%::*}"
-		VALUE="${pkg##*::}"
-		install_npm_packages $KEY $VALUE
-	done
+chapter "Initial ZSH Setup…"
+if [ -e $cwd/materials/dotfiles ]; then
+	
+		if ask "Do you want to install Oh-My-ZSH! and Powerlevel10K theme for the first time?" Y; then
+			install_ohmyzsh;
+			echo "\n";
+			print_success "Installation complete.";
+	
+	else
+		print_success_muted "Installation was declined. Skipped.";
+	fi
+else
+	print_warning "Something went wrong. Skipping."
 fi
-
 
 ###############################################################################
 # LINK: dotfiles
@@ -238,7 +256,6 @@ if [ -e $cwd/materials/dotfiles ]; then
 else
 	print_warning "Something went wrong. Skipping."
 fi
-
 
 ###############################################################################
 # END
